name: deploy to npm

on:
  push:
    branches:
      - publish/setup

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout current
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: publish version
        id: publish_version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: npm version bump
        run: echo ${{ steps.publish_version.outputs.RELEASE_VERSION }}
