name: deploy to npm

on:
  push:
    tags:
      - "*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout current
        uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: publish version
        id: publish_version
        run: echo "RELEASE_VERSION=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      - name: npm version bump
        run: npm version ${{ steps.publish_version.outputs.RELEASE_VERSION }}

      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      #   - name: npm publish
      #     run: npm run publish:npm

      - name: push to github
        run: |
          git add .
          git commit -m "chore: publish version ${{ steps.publish_version.outputs.RELEASE_VERSION }}"
          git push
